FROM node:20-alpine as builder

WORKDIR app

COPY package.json ./

RUN npm install

COPY . .

# RUN npx prisma generate

CMD ["npm", "run", "build"]

FROM node:20-alpine as prod

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/.env* ./

RUN npm install --only=prod

EXPOSE 3000

CMD ["npm", "run", "start"]